---

base_locale: en
locales: [en, fr]

search:
  strict: false
  relative_roots:
    - app/controllers
    - app/helpers
    - app/views
    - app/cells
    - lib/decidim/gallery

ignore_unused:
  - "decidim.components.gallery.name"
  - "decidim.gallery.admin.gallery_item.new.image.title"
  - "decidim.gallery.admin.gallery_item.new.video.title"
  - "decidim.components.gallery.settings.global.*"

ignore_missing:
  - locale.name
